### ISSUE TITLE
TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by jgarzagu** [NVSL/Swoop#15]
***Issue:***
On a fresh install and after executing 
```python 
from Swoop import Swoop
Swoop.EagleFile.from_file('led_smd.sch')
```
Trows the following error in DRU.py:
```
return _compile(pattern, flags).match(string) 
TypeError: cannot use a string pattern on a bytes-like object
```

***Fix:***
Files are open as binary (e.g., open("filename", "rb) ), therefore no string regex is possible on binary strings (e.g. ```b'my string'```). 

DRU.py line 33
``` python
m = re.match("^(\w+)(\[(\w+)\])? = (.*)$", l);
```
should be decoded to a string first
```
m = re.match("^(\w+)(\[(\w+)\])? = (.*)$", l.decode('utf-8')); 
```

**Comment by djmerrill** [comment]
I would decode earlier.
